/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
)

// checks if the SslCertIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SslCertIndex200Response{}

// SslCertIndex200Response struct for SslCertIndex200Response
type SslCertIndex200Response struct {
	Data []Certificate `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
}

// NewSslCertIndex200Response instantiates a new SslCertIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSslCertIndex200Response() *SslCertIndex200Response {
	this := SslCertIndex200Response{}
	return &this
}

// NewSslCertIndex200ResponseWithDefaults instantiates a new SslCertIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSslCertIndex200ResponseWithDefaults() *SslCertIndex200Response {
	this := SslCertIndex200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SslCertIndex200Response) GetData() []Certificate {
	if o == nil || IsNil(o.Data) {
		var ret []Certificate
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslCertIndex200Response) GetDataOk() ([]Certificate, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SslCertIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Certificate and assigns it to the Data field.
func (o *SslCertIndex200Response) SetData(v []Certificate) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SslCertIndex200Response) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SslCertIndex200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *SslCertIndex200Response) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *SslCertIndex200Response) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *SslCertIndex200Response) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *SslCertIndex200Response) UnsetMessage() {
	o.Message.Unset()
}

func (o SslCertIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SslCertIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableSslCertIndex200Response struct {
	value *SslCertIndex200Response
	isSet bool
}

func (v NullableSslCertIndex200Response) Get() *SslCertIndex200Response {
	return v.value
}

func (v *NullableSslCertIndex200Response) Set(val *SslCertIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSslCertIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSslCertIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSslCertIndex200Response(val *SslCertIndex200Response) *NullableSslCertIndex200Response {
	return &NullableSslCertIndex200Response{value: val, isSet: true}
}

func (v NullableSslCertIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSslCertIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


