/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the Subproblem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Subproblem{}

// Subproblem struct for Subproblem
type Subproblem struct {
	// A reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	Identifier *SubproblemIdentifier `json:"identifier,omitempty"`
}

// NewSubproblem instantiates a new Subproblem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubproblem() *Subproblem {
	this := Subproblem{}
	return &this
}

// NewSubproblemWithDefaults instantiates a new Subproblem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubproblemWithDefaults() *Subproblem {
	this := Subproblem{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Subproblem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subproblem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Subproblem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Subproblem) SetType(v string) {
	o.Type = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *Subproblem) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subproblem) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *Subproblem) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *Subproblem) SetDetail(v string) {
	o.Detail = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *Subproblem) GetIdentifier() SubproblemIdentifier {
	if o == nil || IsNil(o.Identifier) {
		var ret SubproblemIdentifier
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subproblem) GetIdentifierOk() (*SubproblemIdentifier, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *Subproblem) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given SubproblemIdentifier and assigns it to the Identifier field.
func (o *Subproblem) SetIdentifier(v SubproblemIdentifier) {
	o.Identifier = &v
}

func (o Subproblem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Subproblem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	return toSerialize, nil
}

type NullableSubproblem struct {
	value *Subproblem
	isSet bool
}

func (v NullableSubproblem) Get() *Subproblem {
	return v.value
}

func (v *NullableSubproblem) Set(val *Subproblem) {
	v.value = val
	v.isSet = true
}

func (v NullableSubproblem) IsSet() bool {
	return v.isSet
}

func (v *NullableSubproblem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubproblem(val *Subproblem) *NullableSubproblem {
	return &NullableSubproblem{value: val, isSet: true}
}

func (v NullableSubproblem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubproblem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


