/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the AccountCertificateOrderIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCertificateOrderIndex200Response{}

// AccountCertificateOrderIndex200Response struct for AccountCertificateOrderIndex200Response
type AccountCertificateOrderIndex200Response struct {
	Data []AccountCertificateOrder `json:"data,omitempty"`
	Links *PaginatedResponseLinks `json:"links,omitempty"`
	Meta *PaginatedResponseMeta `json:"meta,omitempty"`
}

// NewAccountCertificateOrderIndex200Response instantiates a new AccountCertificateOrderIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCertificateOrderIndex200Response() *AccountCertificateOrderIndex200Response {
	this := AccountCertificateOrderIndex200Response{}
	return &this
}

// NewAccountCertificateOrderIndex200ResponseWithDefaults instantiates a new AccountCertificateOrderIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCertificateOrderIndex200ResponseWithDefaults() *AccountCertificateOrderIndex200Response {
	this := AccountCertificateOrderIndex200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AccountCertificateOrderIndex200Response) GetData() []AccountCertificateOrder {
	if o == nil || IsNil(o.Data) {
		var ret []AccountCertificateOrder
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateOrderIndex200Response) GetDataOk() ([]AccountCertificateOrder, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AccountCertificateOrderIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AccountCertificateOrder and assigns it to the Data field.
func (o *AccountCertificateOrderIndex200Response) SetData(v []AccountCertificateOrder) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AccountCertificateOrderIndex200Response) GetLinks() PaginatedResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret PaginatedResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateOrderIndex200Response) GetLinksOk() (*PaginatedResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AccountCertificateOrderIndex200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given PaginatedResponseLinks and assigns it to the Links field.
func (o *AccountCertificateOrderIndex200Response) SetLinks(v PaginatedResponseLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AccountCertificateOrderIndex200Response) GetMeta() PaginatedResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginatedResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateOrderIndex200Response) GetMetaOk() (*PaginatedResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AccountCertificateOrderIndex200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginatedResponseMeta and assigns it to the Meta field.
func (o *AccountCertificateOrderIndex200Response) SetMeta(v PaginatedResponseMeta) {
	o.Meta = &v
}

func (o AccountCertificateOrderIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCertificateOrderIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableAccountCertificateOrderIndex200Response struct {
	value *AccountCertificateOrderIndex200Response
	isSet bool
}

func (v NullableAccountCertificateOrderIndex200Response) Get() *AccountCertificateOrderIndex200Response {
	return v.value
}

func (v *NullableAccountCertificateOrderIndex200Response) Set(val *AccountCertificateOrderIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCertificateOrderIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCertificateOrderIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCertificateOrderIndex200Response(val *AccountCertificateOrderIndex200Response) *NullableAccountCertificateOrderIndex200Response {
	return &NullableAccountCertificateOrderIndex200Response{value: val, isSet: true}
}

func (v NullableAccountCertificateOrderIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCertificateOrderIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


