/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the TrafficsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficsData{}

// TrafficsData struct for TrafficsData
type TrafficsData struct {
	Data *Traffics `json:"data,omitempty"`
}

// NewTrafficsData instantiates a new TrafficsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficsData() *TrafficsData {
	this := TrafficsData{}
	return &this
}

// NewTrafficsDataWithDefaults instantiates a new TrafficsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficsDataWithDefaults() *TrafficsData {
	this := TrafficsData{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TrafficsData) GetData() Traffics {
	if o == nil || IsNil(o.Data) {
		var ret Traffics
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficsData) GetDataOk() (*Traffics, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TrafficsData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Traffics and assigns it to the Data field.
func (o *TrafficsData) SetData(v Traffics) {
	o.Data = &v
}

func (o TrafficsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTrafficsData struct {
	value *TrafficsData
	isSet bool
}

func (v NullableTrafficsData) Get() *TrafficsData {
	return v.value
}

func (v *NullableTrafficsData) Set(val *TrafficsData) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficsData) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficsData(val *TrafficsData) *NullableTrafficsData {
	return &NullableTrafficsData{value: val, isSet: true}
}

func (v NullableTrafficsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


