/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
)

// checks if the MetricExporterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricExporterResponse{}

// MetricExporterResponse struct for MetricExporterResponse
type MetricExporterResponse struct {
	Data *map[string]interface{} `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
}

// NewMetricExporterResponse instantiates a new MetricExporterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricExporterResponse() *MetricExporterResponse {
	this := MetricExporterResponse{}
	return &this
}

// NewMetricExporterResponseWithDefaults instantiates a new MetricExporterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricExporterResponseWithDefaults() *MetricExporterResponse {
	this := MetricExporterResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MetricExporterResponse) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricExporterResponse) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MetricExporterResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *MetricExporterResponse) SetData(v map[string]interface{}) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MetricExporterResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MetricExporterResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *MetricExporterResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *MetricExporterResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *MetricExporterResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *MetricExporterResponse) UnsetMessage() {
	o.Message.Unset()
}

func (o MetricExporterResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricExporterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableMetricExporterResponse struct {
	value *MetricExporterResponse
	isSet bool
}

func (v NullableMetricExporterResponse) Get() *MetricExporterResponse {
	return v.value
}

func (v *NullableMetricExporterResponse) Set(val *MetricExporterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricExporterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricExporterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricExporterResponse(val *MetricExporterResponse) *NullableMetricExporterResponse {
	return &NullableMetricExporterResponse{value: val, isSet: true}
}

func (v NullableMetricExporterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricExporterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


