/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the DomainsClaimsCheck200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainsClaimsCheck200Response{}

// DomainsClaimsCheck200Response struct for DomainsClaimsCheck200Response
type DomainsClaimsCheck200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewDomainsClaimsCheck200Response instantiates a new DomainsClaimsCheck200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainsClaimsCheck200Response() *DomainsClaimsCheck200Response {
	this := DomainsClaimsCheck200Response{}
	return &this
}

// NewDomainsClaimsCheck200ResponseWithDefaults instantiates a new DomainsClaimsCheck200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainsClaimsCheck200ResponseWithDefaults() *DomainsClaimsCheck200Response {
	this := DomainsClaimsCheck200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DomainsClaimsCheck200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainsClaimsCheck200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DomainsClaimsCheck200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DomainsClaimsCheck200Response) SetMessage(v string) {
	o.Message = &v
}

func (o DomainsClaimsCheck200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainsClaimsCheck200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDomainsClaimsCheck200Response struct {
	value *DomainsClaimsCheck200Response
	isSet bool
}

func (v NullableDomainsClaimsCheck200Response) Get() *DomainsClaimsCheck200Response {
	return v.value
}

func (v *NullableDomainsClaimsCheck200Response) Set(val *DomainsClaimsCheck200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainsClaimsCheck200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainsClaimsCheck200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainsClaimsCheck200Response(val *DomainsClaimsCheck200Response) *NullableDomainsClaimsCheck200Response {
	return &NullableDomainsClaimsCheck200Response{value: val, isSet: true}
}

func (v NullableDomainsClaimsCheck200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainsClaimsCheck200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


