/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
)

// checks if the MapTrafficsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapTrafficsData{}

// MapTrafficsData struct for MapTrafficsData
type MapTrafficsData struct {
	Data *TrafficsMap `json:"data,omitempty"`
}

// NewMapTrafficsData instantiates a new MapTrafficsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapTrafficsData() *MapTrafficsData {
	this := MapTrafficsData{}
	return &this
}

// NewMapTrafficsDataWithDefaults instantiates a new MapTrafficsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapTrafficsDataWithDefaults() *MapTrafficsData {
	this := MapTrafficsData{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MapTrafficsData) GetData() TrafficsMap {
	if o == nil || IsNil(o.Data) {
		var ret TrafficsMap
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapTrafficsData) GetDataOk() (*TrafficsMap, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MapTrafficsData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TrafficsMap and assigns it to the Data field.
func (o *MapTrafficsData) SetData(v TrafficsMap) {
	o.Data = &v
}

func (o MapTrafficsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapTrafficsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableMapTrafficsData struct {
	value *MapTrafficsData
	isSet bool
}

func (v NullableMapTrafficsData) Get() *MapTrafficsData {
	return v.value
}

func (v *NullableMapTrafficsData) Set(val *MapTrafficsData) {
	v.value = val
	v.isSet = true
}

func (v NullableMapTrafficsData) IsSet() bool {
	return v.isSet
}

func (v *NullableMapTrafficsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapTrafficsData(val *MapTrafficsData) *NullableMapTrafficsData {
	return &NullableMapTrafficsData{value: val, isSet: true}
}

func (v NullableMapTrafficsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapTrafficsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


