/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the TrafficsMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficsMap{}

// TrafficsMap struct for TrafficsMap
type TrafficsMap struct {
	// Deprecated
	Statistics []CountryStatistics `json:"statistics,omitempty"`
	Charts *TrafficsMapCharts `json:"charts,omitempty"`
	Lists []CountryList `json:"lists,omitempty"`
}

// NewTrafficsMap instantiates a new TrafficsMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficsMap() *TrafficsMap {
	this := TrafficsMap{}
	return &this
}

// NewTrafficsMapWithDefaults instantiates a new TrafficsMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficsMapWithDefaults() *TrafficsMap {
	this := TrafficsMap{}
	return &this
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
// Deprecated
func (o *TrafficsMap) GetStatistics() []CountryStatistics {
	if o == nil || IsNil(o.Statistics) {
		var ret []CountryStatistics
		return ret
	}
	return o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *TrafficsMap) GetStatisticsOk() ([]CountryStatistics, bool) {
	if o == nil || IsNil(o.Statistics) {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *TrafficsMap) HasStatistics() bool {
	if o != nil && !IsNil(o.Statistics) {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given []CountryStatistics and assigns it to the Statistics field.
// Deprecated
func (o *TrafficsMap) SetStatistics(v []CountryStatistics) {
	o.Statistics = v
}

// GetCharts returns the Charts field value if set, zero value otherwise.
func (o *TrafficsMap) GetCharts() TrafficsMapCharts {
	if o == nil || IsNil(o.Charts) {
		var ret TrafficsMapCharts
		return ret
	}
	return *o.Charts
}

// GetChartsOk returns a tuple with the Charts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficsMap) GetChartsOk() (*TrafficsMapCharts, bool) {
	if o == nil || IsNil(o.Charts) {
		return nil, false
	}
	return o.Charts, true
}

// HasCharts returns a boolean if a field has been set.
func (o *TrafficsMap) HasCharts() bool {
	if o != nil && !IsNil(o.Charts) {
		return true
	}

	return false
}

// SetCharts gets a reference to the given TrafficsMapCharts and assigns it to the Charts field.
func (o *TrafficsMap) SetCharts(v TrafficsMapCharts) {
	o.Charts = &v
}

// GetLists returns the Lists field value if set, zero value otherwise.
func (o *TrafficsMap) GetLists() []CountryList {
	if o == nil || IsNil(o.Lists) {
		var ret []CountryList
		return ret
	}
	return o.Lists
}

// GetListsOk returns a tuple with the Lists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficsMap) GetListsOk() ([]CountryList, bool) {
	if o == nil || IsNil(o.Lists) {
		return nil, false
	}
	return o.Lists, true
}

// HasLists returns a boolean if a field has been set.
func (o *TrafficsMap) HasLists() bool {
	if o != nil && !IsNil(o.Lists) {
		return true
	}

	return false
}

// SetLists gets a reference to the given []CountryList and assigns it to the Lists field.
func (o *TrafficsMap) SetLists(v []CountryList) {
	o.Lists = v
}

func (o TrafficsMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficsMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Statistics) {
		toSerialize["statistics"] = o.Statistics
	}
	if !IsNil(o.Charts) {
		toSerialize["charts"] = o.Charts
	}
	if !IsNil(o.Lists) {
		toSerialize["lists"] = o.Lists
	}
	return toSerialize, nil
}

type NullableTrafficsMap struct {
	value *TrafficsMap
	isSet bool
}

func (v NullableTrafficsMap) Get() *TrafficsMap {
	return v.value
}

func (v *NullableTrafficsMap) Set(val *TrafficsMap) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficsMap) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficsMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficsMap(val *TrafficsMap) *NullableTrafficsMap {
	return &NullableTrafficsMap{value: val, isSet: true}
}

func (v NullableTrafficsMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficsMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


