/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferDomainChangeStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferDomainChangeStatus{}

// TransferDomainChangeStatus struct for TransferDomainChangeStatus
type TransferDomainChangeStatus struct {
	Domain string `json:"domain"`
	Status string `json:"status"`
	PreserveState *bool `json:"preserve_state,omitempty"`
}

type _TransferDomainChangeStatus TransferDomainChangeStatus

// NewTransferDomainChangeStatus instantiates a new TransferDomainChangeStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferDomainChangeStatus(domain string, status string) *TransferDomainChangeStatus {
	this := TransferDomainChangeStatus{}
	this.Domain = domain
	this.Status = status
	var preserveState bool = false
	this.PreserveState = &preserveState
	return &this
}

// NewTransferDomainChangeStatusWithDefaults instantiates a new TransferDomainChangeStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferDomainChangeStatusWithDefaults() *TransferDomainChangeStatus {
	this := TransferDomainChangeStatus{}
	var preserveState bool = false
	this.PreserveState = &preserveState
	return &this
}

// GetDomain returns the Domain field value
func (o *TransferDomainChangeStatus) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *TransferDomainChangeStatus) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *TransferDomainChangeStatus) SetDomain(v string) {
	o.Domain = v
}

// GetStatus returns the Status field value
func (o *TransferDomainChangeStatus) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TransferDomainChangeStatus) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TransferDomainChangeStatus) SetStatus(v string) {
	o.Status = v
}

// GetPreserveState returns the PreserveState field value if set, zero value otherwise.
func (o *TransferDomainChangeStatus) GetPreserveState() bool {
	if o == nil || IsNil(o.PreserveState) {
		var ret bool
		return ret
	}
	return *o.PreserveState
}

// GetPreserveStateOk returns a tuple with the PreserveState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferDomainChangeStatus) GetPreserveStateOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveState) {
		return nil, false
	}
	return o.PreserveState, true
}

// HasPreserveState returns a boolean if a field has been set.
func (o *TransferDomainChangeStatus) HasPreserveState() bool {
	if o != nil && !IsNil(o.PreserveState) {
		return true
	}

	return false
}

// SetPreserveState gets a reference to the given bool and assigns it to the PreserveState field.
func (o *TransferDomainChangeStatus) SetPreserveState(v bool) {
	o.PreserveState = &v
}

func (o TransferDomainChangeStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferDomainChangeStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["status"] = o.Status
	if !IsNil(o.PreserveState) {
		toSerialize["preserve_state"] = o.PreserveState
	}
	return toSerialize, nil
}

func (o *TransferDomainChangeStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferDomainChangeStatus := _TransferDomainChangeStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferDomainChangeStatus)

	if err != nil {
		return err
	}

	*o = TransferDomainChangeStatus(varTransferDomainChangeStatus)

	return err
}

type NullableTransferDomainChangeStatus struct {
	value *TransferDomainChangeStatus
	isSet bool
}

func (v NullableTransferDomainChangeStatus) Get() *TransferDomainChangeStatus {
	return v.value
}

func (v *NullableTransferDomainChangeStatus) Set(val *TransferDomainChangeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferDomainChangeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferDomainChangeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferDomainChangeStatus(val *TransferDomainChangeStatus) *NullableTransferDomainChangeStatus {
	return &NullableTransferDomainChangeStatus{value: val, isSet: true}
}

func (v NullableTransferDomainChangeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferDomainChangeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


