/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
)

// checks if the AccountCertificateInstall200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCertificateInstall200Response{}

// AccountCertificateInstall200Response struct for AccountCertificateInstall200Response
type AccountCertificateInstall200Response struct {
	Message *string `json:"message,omitempty"`
	Warnings []AccountCertificateInstall200ResponseWarningsInner `json:"warnings,omitempty"`
}

// NewAccountCertificateInstall200Response instantiates a new AccountCertificateInstall200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCertificateInstall200Response() *AccountCertificateInstall200Response {
	this := AccountCertificateInstall200Response{}
	return &this
}

// NewAccountCertificateInstall200ResponseWithDefaults instantiates a new AccountCertificateInstall200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCertificateInstall200ResponseWithDefaults() *AccountCertificateInstall200Response {
	this := AccountCertificateInstall200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AccountCertificateInstall200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateInstall200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AccountCertificateInstall200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AccountCertificateInstall200Response) SetMessage(v string) {
	o.Message = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *AccountCertificateInstall200Response) GetWarnings() []AccountCertificateInstall200ResponseWarningsInner {
	if o == nil || IsNil(o.Warnings) {
		var ret []AccountCertificateInstall200ResponseWarningsInner
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateInstall200Response) GetWarningsOk() ([]AccountCertificateInstall200ResponseWarningsInner, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *AccountCertificateInstall200Response) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []AccountCertificateInstall200ResponseWarningsInner and assigns it to the Warnings field.
func (o *AccountCertificateInstall200Response) SetWarnings(v []AccountCertificateInstall200ResponseWarningsInner) {
	o.Warnings = v
}

func (o AccountCertificateInstall200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCertificateInstall200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullableAccountCertificateInstall200Response struct {
	value *AccountCertificateInstall200Response
	isSet bool
}

func (v NullableAccountCertificateInstall200Response) Get() *AccountCertificateInstall200Response {
	return v.value
}

func (v *NullableAccountCertificateInstall200Response) Set(val *AccountCertificateInstall200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCertificateInstall200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCertificateInstall200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCertificateInstall200Response(val *AccountCertificateInstall200Response) *NullableAccountCertificateInstall200Response {
	return &NullableAccountCertificateInstall200Response{value: val, isSet: true}
}

func (v NullableAccountCertificateInstall200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCertificateInstall200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


