/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the AggregatedReportsFilterResponsePopsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregatedReportsFilterResponsePopsInner{}

// AggregatedReportsFilterResponsePopsInner struct for AggregatedReportsFilterResponsePopsInner
type AggregatedReportsFilterResponsePopsInner struct {
	Pop *string `json:"pop,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewAggregatedReportsFilterResponsePopsInner instantiates a new AggregatedReportsFilterResponsePopsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregatedReportsFilterResponsePopsInner() *AggregatedReportsFilterResponsePopsInner {
	this := AggregatedReportsFilterResponsePopsInner{}
	return &this
}

// NewAggregatedReportsFilterResponsePopsInnerWithDefaults instantiates a new AggregatedReportsFilterResponsePopsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregatedReportsFilterResponsePopsInnerWithDefaults() *AggregatedReportsFilterResponsePopsInner {
	this := AggregatedReportsFilterResponsePopsInner{}
	return &this
}

// GetPop returns the Pop field value if set, zero value otherwise.
func (o *AggregatedReportsFilterResponsePopsInner) GetPop() string {
	if o == nil || IsNil(o.Pop) {
		var ret string
		return ret
	}
	return *o.Pop
}

// GetPopOk returns a tuple with the Pop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedReportsFilterResponsePopsInner) GetPopOk() (*string, bool) {
	if o == nil || IsNil(o.Pop) {
		return nil, false
	}
	return o.Pop, true
}

// HasPop returns a boolean if a field has been set.
func (o *AggregatedReportsFilterResponsePopsInner) HasPop() bool {
	if o != nil && !IsNil(o.Pop) {
		return true
	}

	return false
}

// SetPop gets a reference to the given string and assigns it to the Pop field.
func (o *AggregatedReportsFilterResponsePopsInner) SetPop(v string) {
	o.Pop = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *AggregatedReportsFilterResponsePopsInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedReportsFilterResponsePopsInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *AggregatedReportsFilterResponsePopsInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *AggregatedReportsFilterResponsePopsInner) SetLabel(v string) {
	o.Label = &v
}

func (o AggregatedReportsFilterResponsePopsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregatedReportsFilterResponsePopsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pop) {
		toSerialize["pop"] = o.Pop
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableAggregatedReportsFilterResponsePopsInner struct {
	value *AggregatedReportsFilterResponsePopsInner
	isSet bool
}

func (v NullableAggregatedReportsFilterResponsePopsInner) Get() *AggregatedReportsFilterResponsePopsInner {
	return v.value
}

func (v *NullableAggregatedReportsFilterResponsePopsInner) Set(val *AggregatedReportsFilterResponsePopsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregatedReportsFilterResponsePopsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregatedReportsFilterResponsePopsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregatedReportsFilterResponsePopsInner(val *AggregatedReportsFilterResponsePopsInner) *NullableAggregatedReportsFilterResponsePopsInner {
	return &NullableAggregatedReportsFilterResponsePopsInner{value: val, isSet: true}
}

func (v NullableAggregatedReportsFilterResponsePopsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregatedReportsFilterResponsePopsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


