/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
)

// checks if the AccountCertificateInstall200ResponseWarningsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCertificateInstall200ResponseWarningsInner{}

// AccountCertificateInstall200ResponseWarningsInner struct for AccountCertificateInstall200ResponseWarningsInner
type AccountCertificateInstall200ResponseWarningsInner struct {
	Domain *string `json:"domain,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewAccountCertificateInstall200ResponseWarningsInner instantiates a new AccountCertificateInstall200ResponseWarningsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCertificateInstall200ResponseWarningsInner() *AccountCertificateInstall200ResponseWarningsInner {
	this := AccountCertificateInstall200ResponseWarningsInner{}
	return &this
}

// NewAccountCertificateInstall200ResponseWarningsInnerWithDefaults instantiates a new AccountCertificateInstall200ResponseWarningsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCertificateInstall200ResponseWarningsInnerWithDefaults() *AccountCertificateInstall200ResponseWarningsInner {
	this := AccountCertificateInstall200ResponseWarningsInner{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *AccountCertificateInstall200ResponseWarningsInner) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateInstall200ResponseWarningsInner) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *AccountCertificateInstall200ResponseWarningsInner) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *AccountCertificateInstall200ResponseWarningsInner) SetDomain(v string) {
	o.Domain = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AccountCertificateInstall200ResponseWarningsInner) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCertificateInstall200ResponseWarningsInner) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AccountCertificateInstall200ResponseWarningsInner) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AccountCertificateInstall200ResponseWarningsInner) SetReason(v string) {
	o.Reason = &v
}

func (o AccountCertificateInstall200ResponseWarningsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCertificateInstall200ResponseWarningsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableAccountCertificateInstall200ResponseWarningsInner struct {
	value *AccountCertificateInstall200ResponseWarningsInner
	isSet bool
}

func (v NullableAccountCertificateInstall200ResponseWarningsInner) Get() *AccountCertificateInstall200ResponseWarningsInner {
	return v.value
}

func (v *NullableAccountCertificateInstall200ResponseWarningsInner) Set(val *AccountCertificateInstall200ResponseWarningsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCertificateInstall200ResponseWarningsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCertificateInstall200ResponseWarningsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCertificateInstall200ResponseWarningsInner(val *AccountCertificateInstall200ResponseWarningsInner) *NullableAccountCertificateInstall200ResponseWarningsInner {
	return &NullableAccountCertificateInstall200ResponseWarningsInner{value: val, isSet: true}
}

func (v NullableAccountCertificateInstall200ResponseWarningsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCertificateInstall200ResponseWarningsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


