/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn-api

import (
	"encoding/json"
	"time"
)

// checks if the AttackReportStatisticsAttacks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttackReportStatisticsAttacks{}

// AttackReportStatisticsAttacks struct for AttackReportStatisticsAttacks
type AttackReportStatisticsAttacks struct {
	TotalAttacks *int64 `json:"total_attacks,omitempty"`
	TopAttacks *time.Time `json:"top_attacks,omitempty"`
}

// NewAttackReportStatisticsAttacks instantiates a new AttackReportStatisticsAttacks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttackReportStatisticsAttacks() *AttackReportStatisticsAttacks {
	this := AttackReportStatisticsAttacks{}
	return &this
}

// NewAttackReportStatisticsAttacksWithDefaults instantiates a new AttackReportStatisticsAttacks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttackReportStatisticsAttacksWithDefaults() *AttackReportStatisticsAttacks {
	this := AttackReportStatisticsAttacks{}
	return &this
}

// GetTotalAttacks returns the TotalAttacks field value if set, zero value otherwise.
func (o *AttackReportStatisticsAttacks) GetTotalAttacks() int64 {
	if o == nil || IsNil(o.TotalAttacks) {
		var ret int64
		return ret
	}
	return *o.TotalAttacks
}

// GetTotalAttacksOk returns a tuple with the TotalAttacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttackReportStatisticsAttacks) GetTotalAttacksOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalAttacks) {
		return nil, false
	}
	return o.TotalAttacks, true
}

// HasTotalAttacks returns a boolean if a field has been set.
func (o *AttackReportStatisticsAttacks) HasTotalAttacks() bool {
	if o != nil && !IsNil(o.TotalAttacks) {
		return true
	}

	return false
}

// SetTotalAttacks gets a reference to the given int64 and assigns it to the TotalAttacks field.
func (o *AttackReportStatisticsAttacks) SetTotalAttacks(v int64) {
	o.TotalAttacks = &v
}

// GetTopAttacks returns the TopAttacks field value if set, zero value otherwise.
func (o *AttackReportStatisticsAttacks) GetTopAttacks() time.Time {
	if o == nil || IsNil(o.TopAttacks) {
		var ret time.Time
		return ret
	}
	return *o.TopAttacks
}

// GetTopAttacksOk returns a tuple with the TopAttacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttackReportStatisticsAttacks) GetTopAttacksOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TopAttacks) {
		return nil, false
	}
	return o.TopAttacks, true
}

// HasTopAttacks returns a boolean if a field has been set.
func (o *AttackReportStatisticsAttacks) HasTopAttacks() bool {
	if o != nil && !IsNil(o.TopAttacks) {
		return true
	}

	return false
}

// SetTopAttacks gets a reference to the given time.Time and assigns it to the TopAttacks field.
func (o *AttackReportStatisticsAttacks) SetTopAttacks(v time.Time) {
	o.TopAttacks = &v
}

func (o AttackReportStatisticsAttacks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttackReportStatisticsAttacks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalAttacks) {
		toSerialize["total_attacks"] = o.TotalAttacks
	}
	if !IsNil(o.TopAttacks) {
		toSerialize["top_attacks"] = o.TopAttacks
	}
	return toSerialize, nil
}

type NullableAttackReportStatisticsAttacks struct {
	value *AttackReportStatisticsAttacks
	isSet bool
}

func (v NullableAttackReportStatisticsAttacks) Get() *AttackReportStatisticsAttacks {
	return v.value
}

func (v *NullableAttackReportStatisticsAttacks) Set(val *AttackReportStatisticsAttacks) {
	v.value = val
	v.isSet = true
}

func (v NullableAttackReportStatisticsAttacks) IsSet() bool {
	return v.isSet
}

func (v *NullableAttackReportStatisticsAttacks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttackReportStatisticsAttacks(val *AttackReportStatisticsAttacks) *NullableAttackReportStatisticsAttacks {
	return &NullableAttackReportStatisticsAttacks{value: val, isSet: true}
}

func (v NullableAttackReportStatisticsAttacks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttackReportStatisticsAttacks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


