/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdnapi

import (
	"encoding/json"
)

// checks if the DomainClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainClaimRequest{}

// DomainClaimRequest struct for DomainClaimRequest
type DomainClaimRequest struct {
	// name of claiming domain
	Domain *string `json:"domain,omitempty"`
}

// NewDomainClaimRequest instantiates a new DomainClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainClaimRequest() *DomainClaimRequest {
	this := DomainClaimRequest{}
	return &this
}

// NewDomainClaimRequestWithDefaults instantiates a new DomainClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainClaimRequestWithDefaults() *DomainClaimRequest {
	this := DomainClaimRequest{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *DomainClaimRequest) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainClaimRequest) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *DomainClaimRequest) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *DomainClaimRequest) SetDomain(v string) {
	o.Domain = &v
}

func (o DomainClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

type NullableDomainClaimRequest struct {
	value *DomainClaimRequest
	isSet bool
}

func (v NullableDomainClaimRequest) Get() *DomainClaimRequest {
	return v.value
}

func (v *NullableDomainClaimRequest) Set(val *DomainClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainClaimRequest(val *DomainClaimRequest) *NullableDomainClaimRequest {
	return &NullableDomainClaimRequest{value: val, isSet: true}
}

func (v NullableDomainClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


